stages:
  - build
  - test

#################### BUILD STAGE ####################
build_mist_image:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - docker build --rm -t gcr.io/mist-ops/mist:io-$CI_COMMIT_SHA .
    - docker tag gcr.io/mist-ops/mist:io-$CI_COMMIT_SHA gcr.io/mist-ops/mist:io-$CI_COMMIT_REF_SLUG
    - docker tag gcr.io/mist-ops/mist:io-$CI_COMMIT_SHA mist/mist:io-$CI_COMMIT_SHA
    - docker tag gcr.io/mist-ops/mist:io-$CI_COMMIT_REF_SLUG mist/mist:io-$CI_COMMIT_REF_SLUG
    - docker push gcr.io/mist-ops/mist:io-$CI_COMMIT_SHA
    - docker push gcr.io/mist-ops/mist:io-$CI_COMMIT_REF_SLUG
    - docker push mist/mist:io-$CI_COMMIT_SHA
    - docker push mist/mist:io-$CI_COMMIT_REF_SLUG
  tags:
    - builder
  dependencies: []


#################### TEST STAGE ####################
flake8:
  stage: test
  image: python:2.7-alpine
  before_script:
    - pip install flake8
  script:
    - flake8
